### ISSUE TITLE
Active repo or accepting pull requests?

### ISSUE THREAD

**Issue by leoromanovsky** [mesoshq/metronome#3]
Hello,

I noticed that metronome 0.4.0 is released but not reflected here. Are you accepting pull requests for it?

**Comment by tobilg** [comment]
Yes, I‘m accepting pull requests. Feel free to open a PR. Thanks in advance!

**Comment by tobilg** [comment]
I updated this project to use Mesos 1.5.0 and Metronome 0.4.1. The Docker image is just being built.
